/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-green": {
          50: "#e6f4f0",
          100: "#d1f0e8",
          200: "#a3e0d1",
          300: "#75d1ba",
          400: "#47c1a3",
          500: "#19705D", // base color
          600: "#14584b",
          700: "#0f4038",
          800: "#0a2826",
          900: "#051013",
        },
      },
    },
  },
  safelist: [
    // ============ PRIMARY-GREEN ============
    // Background colors
    "bg-primary-green-50",
    "bg-primary-green-100",
    "bg-primary-green-200",
    "bg-primary-green-300",
    "bg-primary-green-400",
    "bg-primary-green-500",
    "bg-primary-green-600",
    "bg-primary-green-700",
    "bg-primary-green-800",
    "bg-primary-green-900",

    // Dark mode backgrounds
    "dark:bg-primary-green-50",
    "dark:bg-primary-green-100",
    "dark:bg-primary-green-200",
    "dark:bg-primary-green-300",
    "dark:bg-primary-green-400",
    "dark:bg-primary-green-500",
    "dark:bg-primary-green-600",
    "dark:bg-primary-green-700",
    "dark:bg-primary-green-800",
    "dark:bg-primary-green-900",

    // Hover backgrounds
    "hover:bg-primary-green-50",
    "hover:bg-primary-green-100",
    "hover:bg-primary-green-200",
    "hover:bg-primary-green-300",
    "hover:bg-primary-green-400",
    "hover:bg-primary-green-500",
    "hover:bg-primary-green-600",
    "hover:bg-primary-green-700",
    "hover:bg-primary-green-800",
    "hover:bg-primary-green-900",

    // Dark hover backgrounds
    "dark:hover:bg-primary-green-50",
    "dark:hover:bg-primary-green-100",
    "dark:hover:bg-primary-green-200",
    "dark:hover:bg-primary-green-300",
    "dark:hover:bg-primary-green-400",
    "dark:hover:bg-primary-green-500",
    "dark:hover:bg-primary-green-600",
    "dark:hover:bg-primary-green-700",
    "dark:hover:bg-primary-green-800",
    "dark:hover:bg-primary-green-900",

    // Text colors
    "text-primary-green-50",
    "text-primary-green-100",
    "text-primary-green-200",
    "text-primary-green-300",
    "text-primary-green-400",
    "text-primary-green-500",
    "text-primary-green-600",
    "text-primary-green-700",
    "text-primary-green-800",
    "text-primary-green-900",

    // Dark text colors
    "dark:text-primary-green-50",
    "dark:text-primary-green-100",
    "dark:text-primary-green-200",
    "dark:text-primary-green-300",
    "dark:text-primary-green-400",
    "dark:text-primary-green-500",
    "dark:text-primary-green-600",
    "dark:text-primary-green-700",
    "dark:text-primary-green-800",
    "dark:text-primary-green-900",

    // Hover text colors
    "hover:text-primary-green-50",
    "hover:text-primary-green-100",
    "hover:text-primary-green-200",
    "hover:text-primary-green-300",
    "hover:text-primary-green-400",
    "hover:text-primary-green-500",
    "hover:text-primary-green-600",
    "hover:text-primary-green-700",
    "hover:text-primary-green-800",
    "hover:text-primary-green-900",

    // Dark hover text colors
    "dark:hover:text-primary-green-50",
    "dark:hover:text-primary-green-100",
    "dark:hover:text-primary-green-200",
    "dark:hover:text-primary-green-300",
    "dark:hover:text-primary-green-400",
    "dark:hover:text-primary-green-500",
    "dark:hover:text-primary-green-600",
    "dark:hover:text-primary-green-700",
    "dark:hover:text-primary-green-800",
    "dark:hover:text-primary-green-900",

    // Border colors
    "border-primary-green-50",
    "border-primary-green-100",
    "border-primary-green-200",
    "border-primary-green-300",
    "border-primary-green-400",
    "border-primary-green-500",
    "border-primary-green-600",
    "border-primary-green-700",
    "border-primary-green-800",
    "border-primary-green-900",

    // Dark border colors
    "dark:border-primary-green-50",
    "dark:border-primary-green-100",
    "dark:border-primary-green-200",
    "dark:border-primary-green-300",
    "dark:border-primary-green-400",
    "dark:border-primary-green-500",
    "dark:border-primary-green-600",
    "dark:border-primary-green-700",
    "dark:border-primary-green-800",
    "dark:border-primary-green-900",

    // Hover border colors
    "hover:border-primary-green-50",
    "hover:border-primary-green-100",
    "hover:border-primary-green-200",
    "hover:border-primary-green-300",
    "hover:border-primary-green-400",
    "hover:border-primary-green-500",
    "hover:border-primary-green-600",
    "hover:border-primary-green-700",
    "hover:border-primary-green-800",
    "hover:border-primary-green-900",

    // Focus border
    "focus:border-primary-green-50",
    "focus:border-primary-green-100",
    "focus:border-primary-green-200",
    "focus:border-primary-green-300",
    "focus:border-primary-green-400",
    "focus:border-primary-green-500",
    "focus:border-primary-green-600",
    "focus:border-primary-green-700",
    "focus:border-primary-green-800",
    "focus:border-primary-green-900",

    // Dark focus border
    "dark:focus:border-primary-green-50",
    "dark:focus:border-primary-green-100",
    "dark:focus:border-primary-green-200",
    "dark:focus:border-primary-green-300",
    "dark:focus:border-primary-green-400",
    "dark:focus:border-primary-green-500",
    "dark:focus:border-primary-green-600",
    "dark:focus:border-primary-green-700",
    "dark:focus:border-primary-green-800",
    "dark:focus:border-primary-green-900",

    // Border bottom
    "border-b-2 border-primary-green-50",
    "border-b-2 border-primary-green-100",
    "border-b-2 border-primary-green-200",
    "border-b-2 border-primary-green-300",
    "border-b-2 border-primary-green-400",
    "border-b-2 border-primary-green-500",
    "border-b-2 border-primary-green-600",
    "border-b-2 border-primary-green-700",
    "border-b-2 border-primary-green-800",
    "border-b-2 border-primary-green-900",

    // Border start (right in RTL)
    "border-s-primary-green-50",
    "border-s-primary-green-100",
    "border-s-primary-green-200",
    "border-s-primary-green-300",
    "border-s-primary-green-400",
    "border-s-primary-green-500",
    "border-s-primary-green-600",
    "border-s-primary-green-700",
    "border-s-primary-green-800",
    "border-s-primary-green-900",

    // Marker colors (for list items)
    "marker:text-primary-green-50",
    "marker:text-primary-green-100",
    "marker:text-primary-green-200",
    "marker:text-primary-green-300",
    "marker:text-primary-green-400",
    "marker:text-primary-green-500",
    "marker:text-primary-green-600",
    "marker:text-primary-green-700",
    "marker:text-primary-green-800",
    "marker:text-primary-green-900",

    // Accent colors
    "accent-primary-green-50",
    "accent-primary-green-100",
    "accent-primary-green-200",
    "accent-primary-green-300",
    "accent-primary-green-400",
    "accent-primary-green-500",
    "accent-primary-green-600",
    "accent-primary-green-700",
    "accent-primary-green-800",
    "accent-primary-green-900",

    // Gradients with primary-green
    "from-primary-green-50",
    "from-primary-green-100",
    "from-primary-green-200",
    "from-primary-green-300",
    "from-primary-green-400",
    "from-primary-green-500",
    "from-primary-green-600",
    "from-primary-green-700",
    "from-primary-green-800",
    "from-primary-green-900",

    "to-primary-green-50",
    "to-primary-green-100",
    "to-primary-green-200",
    "to-primary-green-300",
    "to-primary-green-400",
    "to-primary-green-500",
    "to-primary-green-600",
    "to-primary-green-700",
    "to-primary-green-800",
    "to-primary-green-900",

    "bg-gradient-to-br from-primary-green-50",
    "bg-gradient-to-br from-primary-green-100",
    "bg-gradient-to-br from-primary-green-200",
    "bg-gradient-to-br from-primary-green-300",
    "bg-gradient-to-br from-primary-green-400",
    "bg-gradient-to-br from-primary-green-500",
    "bg-gradient-to-br from-primary-green-600",
    "bg-gradient-to-br from-primary-green-700",
    "bg-gradient-to-br from-primary-green-800",
    "bg-gradient-to-br from-primary-green-900",

    // ============ ORANGE ============
    "bg-orange-50",
    "bg-orange-100",
    "bg-orange-200",
    "bg-orange-300",
    "bg-orange-400",
    "bg-orange-500",
    "bg-orange-600",
    "bg-orange-700",
    "bg-orange-800",
    "bg-orange-900",
    "dark:bg-orange-50",
    "dark:bg-orange-100",
    "dark:bg-orange-200",
    "dark:bg-orange-300",
    "dark:bg-orange-400",
    "dark:bg-orange-500",
    "dark:bg-orange-600",
    "dark:bg-orange-700",
    "dark:bg-orange-800",
    "dark:bg-orange-900",
    "hover:bg-orange-50",
    "hover:bg-orange-100",
    "hover:bg-orange-200",
    "hover:bg-orange-300",
    "hover:bg-orange-400",
    "hover:bg-orange-500",
    "hover:bg-orange-600",
    "hover:bg-orange-700",
    "hover:bg-orange-800",
    "hover:bg-orange-900",
    "dark:hover:bg-orange-50",
    "dark:hover:bg-orange-100",
    "dark:hover:bg-orange-200",
    "dark:hover:bg-orange-300",
    "dark:hover:bg-orange-400",
    "dark:hover:bg-orange-500",
    "dark:hover:bg-orange-600",
    "dark:hover:bg-orange-700",
    "dark:hover:bg-orange-800",
    "dark:hover:bg-orange-900",
    "text-orange-50",
    "text-orange-100",
    "text-orange-200",
    "text-orange-300",
    "text-orange-400",
    "text-orange-500",
    "text-orange-600",
    "text-orange-700",
    "text-orange-800",
    "text-orange-900",
    "dark:text-orange-50",
    "dark:text-orange-100",
    "dark:text-orange-200",
    "dark:text-orange-300",
    "dark:text-orange-400",
    "dark:text-orange-500",
    "dark:text-orange-600",
    "dark:text-orange-700",
    "dark:text-orange-800",
    "dark:text-orange-900",
    "hover:text-orange-50",
    "hover:text-orange-100",
    "hover:text-orange-200",
    "hover:text-orange-300",
    "hover:text-orange-400",
    "hover:text-orange-500",
    "hover:text-orange-600",
    "hover:text-orange-700",
    "hover:text-orange-800",
    "hover:text-orange-900",
    "dark:hover:text-orange-50",
    "dark:hover:text-orange-100",
    "dark:hover:text-orange-200",
    "dark:hover:text-orange-300",
    "dark:hover:text-orange-400",
    "dark:hover:text-orange-500",
    "dark:hover:text-orange-600",
    "dark:hover:text-orange-700",
    "dark:hover:text-orange-800",
    "dark:hover:text-orange-900",
    "border-orange-50",
    "border-orange-100",
    "border-orange-200",
    "border-orange-300",
    "border-orange-400",
    "border-orange-500",
    "border-orange-600",
    "border-orange-700",
    "border-orange-800",
    "border-orange-900",
    "dark:border-orange-50",
    "dark:border-orange-100",
    "dark:border-orange-200",
    "dark:border-orange-300",
    "dark:border-orange-400",
    "dark:border-orange-500",
    "dark:border-orange-600",
    "dark:border-orange-700",
    "dark:border-orange-800",
    "dark:border-orange-900",
    "hover:border-orange-50",
    "hover:border-orange-100",
    "hover:border-orange-200",
    "hover:border-orange-300",
    "hover:border-orange-400",
    "hover:border-orange-500",
    "hover:border-orange-600",
    "hover:border-orange-700",
    "hover:border-orange-800",
    "hover:border-orange-900",
    "focus:border-orange-50",
    "focus:border-orange-100",
    "focus:border-orange-200",
    "focus:border-orange-300",
    "focus:border-orange-400",
    "focus:border-orange-500",
    "focus:border-orange-600",
    "focus:border-orange-700",
    "focus:border-orange-800",
    "focus:border-orange-900",
    "dark:focus:border-orange-50",
    "dark:focus:border-orange-100",
    "dark:focus:border-orange-200",
    "dark:focus:border-orange-300",
    "dark:focus:border-orange-400",
    "dark:focus:border-orange-500",
    "dark:focus:border-orange-600",
    "dark:focus:border-orange-700",
    "dark:focus:border-orange-800",
    "dark:focus:border-orange-900",
    "border-b-2 border-orange-50",
    "border-b-2 border-orange-100",
    "border-b-2 border-orange-200",
    "border-b-2 border-orange-300",
    "border-b-2 border-orange-400",
    "border-b-2 border-orange-500",
    "border-b-2 border-orange-600",
    "border-b-2 border-orange-700",
    "border-b-2 border-orange-800",
    "border-b-2 border-orange-900",
    "border-s-orange-50",
    "border-s-orange-100",
    "border-s-orange-200",
    "border-s-orange-300",
    "border-s-orange-400",
    "border-s-orange-500",
    "border-s-orange-600",
    "border-s-orange-700",
    "border-s-orange-800",
    "border-s-orange-900",
    "marker:text-orange-50",
    "marker:text-orange-100",
    "marker:text-orange-200",
    "marker:text-orange-300",
    "marker:text-orange-400",
    "marker:text-orange-500",
    "marker:text-orange-600",
    "marker:text-orange-700",
    "marker:text-orange-800",
    "marker:text-orange-900",
    "accent-orange-50",
    "accent-orange-100",
    "accent-orange-200",
    "accent-orange-300",
    "accent-orange-400",
    "accent-orange-500",
    "accent-orange-600",
    "accent-orange-700",
    "accent-orange-800",
    "accent-orange-900",
    "from-orange-50",
    "from-orange-100",
    "from-orange-200",
    "from-orange-300",
    "from-orange-400",
    "from-orange-500",
    "from-orange-600",
    "from-orange-700",
    "from-orange-800",
    "from-orange-900",
    "to-orange-50",
    "to-orange-100",
    "to-orange-200",
    "to-orange-300",
    "to-orange-400",
    "to-orange-500",
    "to-orange-600",
    "to-orange-700",
    "to-orange-800",
    "to-orange-900",
    "bg-gradient-to-br from-orange-50",
    "bg-gradient-to-br from-orange-100",
    "bg-gradient-to-br from-orange-200",
    "bg-gradient-to-br from-orange-300",
    "bg-gradient-to-br from-orange-400",
    "bg-gradient-to-br from-orange-500",
    "bg-gradient-to-br from-orange-600",
    "bg-gradient-to-br from-orange-700",
    "bg-gradient-to-br from-orange-800",
    "bg-gradient-to-br from-orange-900",

    // ============ BLUE ============
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-200",
    "bg-blue-300",
    "bg-blue-400",
    "bg-blue-500",
    "bg-blue-600",
    "bg-blue-700",
    "bg-blue-800",
    "bg-blue-900",
    "dark:bg-blue-50",
    "dark:bg-blue-100",
    "dark:bg-blue-200",
    "dark:bg-blue-300",
    "dark:bg-blue-400",
    "dark:bg-blue-500",
    "dark:bg-blue-600",
    "dark:bg-blue-700",
    "dark:bg-blue-800",
    "dark:bg-blue-900",
    "hover:bg-blue-50",
    "hover:bg-blue-100",
    "hover:bg-blue-200",
    "hover:bg-blue-300",
    "hover:bg-blue-400",
    "hover:bg-blue-500",
    "hover:bg-blue-600",
    "hover:bg-blue-700",
    "hover:bg-blue-800",
    "hover:bg-blue-900",
    "dark:hover:bg-blue-50",
    "dark:hover:bg-blue-100",
    "dark:hover:bg-blue-200",
    "dark:hover:bg-blue-300",
    "dark:hover:bg-blue-400",
    "dark:hover:bg-blue-500",
    "dark:hover:bg-blue-600",
    "dark:hover:bg-blue-700",
    "dark:hover:bg-blue-800",
    "dark:hover:bg-blue-900",
    "text-blue-50",
    "text-blue-100",
    "text-blue-200",
    "text-blue-300",
    "text-blue-400",
    "text-blue-500",
    "text-blue-600",
    "text-blue-700",
    "text-blue-800",
    "text-blue-900",
    "dark:text-blue-50",
    "dark:text-blue-100",
    "dark:text-blue-200",
    "dark:text-blue-300",
    "dark:text-blue-400",
    "dark:text-blue-500",
    "dark:text-blue-600",
    "dark:text-blue-700",
    "dark:text-blue-800",
    "dark:text-blue-900",
    "hover:text-blue-50",
    "hover:text-blue-100",
    "hover:text-blue-200",
    "hover:text-blue-300",
    "hover:text-blue-400",
    "hover:text-blue-500",
    "hover:text-blue-600",
    "hover:text-blue-700",
    "hover:text-blue-800",
    "hover:text-blue-900",
    "dark:hover:text-blue-50",
    "dark:hover:text-blue-100",
    "dark:hover:text-blue-200",
    "dark:hover:text-blue-300",
    "dark:hover:text-blue-400",
    "dark:hover:text-blue-500",
    "dark:hover:text-blue-600",
    "dark:hover:text-blue-700",
    "dark:hover:text-blue-800",
    "dark:hover:text-blue-900",
    "border-blue-50",
    "border-blue-100",
    "border-blue-200",
    "border-blue-300",
    "border-blue-400",
    "border-blue-500",
    "border-blue-600",
    "border-blue-700",
    "border-blue-800",
    "border-blue-900",
    "dark:border-blue-50",
    "dark:border-blue-100",
    "dark:border-blue-200",
    "dark:border-blue-300",
    "dark:border-blue-400",
    "dark:border-blue-500",
    "dark:border-blue-600",
    "dark:border-blue-700",
    "dark:border-blue-800",
    "dark:border-blue-900",
    "hover:border-blue-50",
    "hover:border-blue-100",
    "hover:border-blue-200",
    "hover:border-blue-300",
    "hover:border-blue-400",
    "hover:border-blue-500",
    "hover:border-blue-600",
    "hover:border-blue-700",
    "hover:border-blue-800",
    "hover:border-blue-900",
    "focus:border-blue-50",
    "focus:border-blue-100",
    "focus:border-blue-200",
    "focus:border-blue-300",
    "focus:border-blue-400",
    "focus:border-blue-500",
    "focus:border-blue-600",
    "focus:border-blue-700",
    "focus:border-blue-800",
    "focus:border-blue-900",
    "dark:focus:border-blue-50",
    "dark:focus:border-blue-100",
    "dark:focus:border-blue-200",
    "dark:focus:border-blue-300",
    "dark:focus:border-blue-400",
    "dark:focus:border-blue-500",
    "dark:focus:border-blue-600",
    "dark:focus:border-blue-700",
    "dark:focus:border-blue-800",
    "dark:focus:border-blue-900",
    "border-b-2 border-blue-50",
    "border-b-2 border-blue-100",
    "border-b-2 border-blue-200",
    "border-b-2 border-blue-300",
    "border-b-2 border-blue-400",
    "border-b-2 border-blue-500",
    "border-b-2 border-blue-600",
    "border-b-2 border-blue-700",
    "border-b-2 border-blue-800",
    "border-b-2 border-blue-900",
    "border-s-blue-50",
    "border-s-blue-100",
    "border-s-blue-200",
    "border-s-blue-300",
    "border-s-blue-400",
    "border-s-blue-500",
    "border-s-blue-600",
    "border-s-blue-700",
    "border-s-blue-800",
    "border-s-blue-900",
    "marker:text-blue-50",
    "marker:text-blue-100",
    "marker:text-blue-200",
    "marker:text-blue-300",
    "marker:text-blue-400",
    "marker:text-blue-500",
    "marker:text-blue-600",
    "marker:text-blue-700",
    "marker:text-blue-800",
    "marker:text-blue-900",
    "accent-blue-50",
    "accent-blue-100",
    "accent-blue-200",
    "accent-blue-300",
    "accent-blue-400",
    "accent-blue-500",
    "accent-blue-600",
    "accent-blue-700",
    "accent-blue-800",
    "accent-blue-900",
    "from-blue-50",
    "from-blue-100",
    "from-blue-200",
    "from-blue-300",
    "from-blue-400",
    "from-blue-500",
    "from-blue-600",
    "from-blue-700",
    "from-blue-800",
    "from-blue-900",
    "to-blue-50",
    "to-blue-100",
    "to-blue-200",
    "to-blue-300",
    "to-blue-400",
    "to-blue-500",
    "to-blue-600",
    "to-blue-700",
    "to-blue-800",
    "to-blue-900",
    "bg-gradient-to-br from-blue-50",
    "bg-gradient-to-br from-blue-100",
    "bg-gradient-to-br from-blue-200",
    "bg-gradient-to-br from-blue-300",
    "bg-gradient-to-br from-blue-400",
    "bg-gradient-to-br from-blue-500",
    "bg-gradient-to-br from-blue-600",
    "bg-gradient-to-br from-blue-700",
    "bg-gradient-to-br from-blue-800",
    "bg-gradient-to-br from-blue-900",

    // ============ RED ============
    "bg-red-50",
    "bg-red-100",
    "bg-red-200",
    "bg-red-300",
    "bg-red-400",
    "bg-red-500",
    "bg-red-600",
    "bg-red-700",
    "bg-red-800",
    "bg-red-900",
    "dark:bg-red-50",
    "dark:bg-red-100",
    "dark:bg-red-200",
    "dark:bg-red-300",
    "dark:bg-red-400",
    "dark:bg-red-500",
    "dark:bg-red-600",
    "dark:bg-red-700",
    "dark:bg-red-800",
    "dark:bg-red-900",
    "hover:bg-red-50",
    "hover:bg-red-100",
    "hover:bg-red-200",
    "hover:bg-red-300",
    "hover:bg-red-400",
    "hover:bg-red-500",
    "hover:bg-red-600",
    "hover:bg-red-700",
    "hover:bg-red-800",
    "hover:bg-red-900",
    "dark:hover:bg-red-50",
    "dark:hover:bg-red-100",
    "dark:hover:bg-red-200",
    "dark:hover:bg-red-300",
    "dark:hover:bg-red-400",
    "dark:hover:bg-red-500",
    "dark:hover:bg-red-600",
    "dark:hover:bg-red-700",
    "dark:hover:bg-red-800",
    "dark:hover:bg-red-900",
    "text-red-50",
    "text-red-100",
    "text-red-200",
    "text-red-300",
    "text-red-400",
    "text-red-500",
    "text-red-600",
    "text-red-700",
    "text-red-800",
    "text-red-900",
    "dark:text-red-50",
    "dark:text-red-100",
    "dark:text-red-200",
    "dark:text-red-300",
    "dark:text-red-400",
    "dark:text-red-500",
    "dark:text-red-600",
    "dark:text-red-700",
    "dark:text-red-800",
    "dark:text-red-900",
    "hover:text-red-50",
    "hover:text-red-100",
    "hover:text-red-200",
    "hover:text-red-300",
    "hover:text-red-400",
    "hover:text-red-500",
    "hover:text-red-600",
    "hover:text-red-700",
    "hover:text-red-800",
    "hover:text-red-900",
    "dark:hover:text-red-50",
    "dark:hover:text-red-100",
    "dark:hover:text-red-200",
    "dark:hover:text-red-300",
    "dark:hover:text-red-400",
    "dark:hover:text-red-500",
    "dark:hover:text-red-600",
    "dark:hover:text-red-700",
    "dark:hover:text-red-800",
    "dark:hover:text-red-900",
    "border-red-50",
    "border-red-100",
    "border-red-200",
    "border-red-300",
    "border-red-400",
    "border-red-500",
    "border-red-600",
    "border-red-700",
    "border-red-800",
    "border-red-900",
    "dark:border-red-50",
    "dark:border-red-100",
    "dark:border-red-200",
    "dark:border-red-300",
    "dark:border-red-400",
    "dark:border-red-500",
    "dark:border-red-600",
    "dark:border-red-700",
    "dark:border-red-800",
    "dark:border-red-900",
    "hover:border-red-50",
    "hover:border-red-100",
    "hover:border-red-200",
    "hover:border-red-300",
    "hover:border-red-400",
    "hover:border-red-500",
    "hover:border-red-600",
    "hover:border-red-700",
    "hover:border-red-800",
    "hover:border-red-900",
    "focus:border-red-50",
    "focus:border-red-100",
    "focus:border-red-200",
    "focus:border-red-300",
    "focus:border-red-400",
    "focus:border-red-500",
    "focus:border-red-600",
    "focus:border-red-700",
    "focus:border-red-800",
    "focus:border-red-900",
    "dark:focus:border-red-50",
    "dark:focus:border-red-100",
    "dark:focus:border-red-200",
    "dark:focus:border-red-300",
    "dark:focus:border-red-400",
    "dark:focus:border-red-500",
    "dark:focus:border-red-600",
    "dark:focus:border-red-700",
    "dark:focus:border-red-800",
    "dark:focus:border-red-900",
    "border-b-2 border-red-50",
    "border-b-2 border-red-100",
    "border-b-2 border-red-200",
    "border-b-2 border-red-300",
    "border-b-2 border-red-400",
    "border-b-2 border-red-500",
    "border-b-2 border-red-600",
    "border-b-2 border-red-700",
    "border-b-2 border-red-800",
    "border-b-2 border-red-900",
    "border-s-red-50",
    "border-s-red-100",
    "border-s-red-200",
    "border-s-red-300",
    "border-s-red-400",
    "border-s-red-500",
    "border-s-red-600",
    "border-s-red-700",
    "border-s-red-800",
    "border-s-red-900",
    "marker:text-red-50",
    "marker:text-red-100",
    "marker:text-red-200",
    "marker:text-red-300",
    "marker:text-red-400",
    "marker:text-red-500",
    "marker:text-red-600",
    "marker:text-red-700",
    "marker:text-red-800",
    "marker:text-red-900",
    "accent-red-50",
    "accent-red-100",
    "accent-red-200",
    "accent-red-300",
    "accent-red-400",
    "accent-red-500",
    "accent-red-600",
    "accent-red-700",
    "accent-red-800",
    "accent-red-900",
    "from-red-50",
    "from-red-100",
    "from-red-200",
    "from-red-300",
    "from-red-400",
    "from-red-500",
    "from-red-600",
    "from-red-700",
    "from-red-800",
    "from-red-900",
    "to-red-50",
    "to-red-100",
    "to-red-200",
    "to-red-300",
    "to-red-400",
    "to-red-500",
    "to-red-600",
    "to-red-700",
    "to-red-800",
    "to-red-900",
    "bg-gradient-to-br from-red-50",
    "bg-gradient-to-br from-red-100",
    "bg-gradient-to-br from-red-200",
    "bg-gradient-to-br from-red-300",
    "bg-gradient-to-br from-red-400",
    "bg-gradient-to-br from-red-500",
    "bg-gradient-to-br from-red-600",
    "bg-gradient-to-br from-red-700",
    "bg-gradient-to-br from-red-800",
    "bg-gradient-to-br from-red-900",

    // ============ GREEN ============
    "bg-green-50",
    "bg-green-100",
    "bg-green-200",
    "bg-green-300",
    "bg-green-400",
    "bg-green-500",
    "bg-green-600",
    "bg-green-700",
    "bg-green-800",
    "bg-green-900",
    "dark:bg-green-50",
    "dark:bg-green-100",
    "dark:bg-green-200",
    "dark:bg-green-300",
    "dark:bg-green-400",
    "dark:bg-green-500",
    "dark:bg-green-600",
    "dark:bg-green-700",
    "dark:bg-green-800",
    "dark:bg-green-900",
    "hover:bg-green-50",
    "hover:bg-green-100",
    "hover:bg-green-200",
    "hover:bg-green-300",
    "hover:bg-green-400",
    "hover:bg-green-500",
    "hover:bg-green-600",
    "hover:bg-green-700",
    "hover:bg-green-800",
    "hover:bg-green-900",
    "dark:hover:bg-green-50",
    "dark:hover:bg-green-100",
    "dark:hover:bg-green-200",
    "dark:hover:bg-green-300",
    "dark:hover:bg-green-400",
    "dark:hover:bg-green-500",
    "dark:hover:bg-green-600",
    "dark:hover:bg-green-700",
    "dark:hover:bg-green-800",
    "dark:hover:bg-green-900",
    "text-green-50",
    "text-green-100",
    "text-green-200",
    "text-green-300",
    "text-green-400",
    "text-green-500",
    "text-green-600",
    "text-green-700",
    "text-green-800",
    "text-green-900",
    "dark:text-green-50",
    "dark:text-green-100",
    "dark:text-green-200",
    "dark:text-green-300",
    "dark:text-green-400",
    "dark:text-green-500",
    "dark:text-green-600",
    "dark:text-green-700",
    "dark:text-green-800",
    "dark:text-green-900",
    "hover:text-green-50",
    "hover:text-green-100",
    "hover:text-green-200",
    "hover:text-green-300",
    "hover:text-green-400",
    "hover:text-green-500",
    "hover:text-green-600",
    "hover:text-green-700",
    "hover:text-green-800",
    "hover:text-green-900",
    "dark:hover:text-green-50",
    "dark:hover:text-green-100",
    "dark:hover:text-green-200",
    "dark:hover:text-green-300",
    "dark:hover:text-green-400",
    "dark:hover:text-green-500",
    "dark:hover:text-green-600",
    "dark:hover:text-green-700",
    "dark:hover:text-green-800",
    "dark:hover:text-green-900",
    "border-green-50",
    "border-green-100",
    "border-green-200",
    "border-green-300",
    "border-green-400",
    "border-green-500",
    "border-green-600",
    "border-green-700",
    "border-green-800",
    "border-green-900",
    "dark:border-green-50",
    "dark:border-green-100",
    "dark:border-green-200",
    "dark:border-green-300",
    "dark:border-green-400",
    "dark:border-green-500",
    "dark:border-green-600",
    "dark:border-green-700",
    "dark:border-green-800",
    "dark:border-green-900",
    "hover:border-green-50",
    "hover:border-green-100",
    "hover:border-green-200",
    "hover:border-green-300",
    "hover:border-green-400",
    "hover:border-green-500",
    "hover:border-green-600",
    "hover:border-green-700",
    "hover:border-green-800",
    "hover:border-green-900",
    "focus:border-green-50",
    "focus:border-green-100",
    "focus:border-green-200",
    "focus:border-green-300",
    "focus:border-green-400",
    "focus:border-green-500",
    "focus:border-green-600",
    "focus:border-green-700",
    "focus:border-green-800",
    "focus:border-green-900",
    "dark:focus:border-green-50",
    "dark:focus:border-green-100",
  ],
};
